### ISSUE TITLE
Utility Viewer - Find Existing Plans, Implement date wrong for user...

### ISSUE THREAD

**Issue by DaveThomKCI** [JMurk/Utility_Viewer_Issues#194]
Sewelo Keleagetse and Chad Fuhrman (both with Wachs) both encounter an error when searching for existing shutdown plans.  When they pull up the window, and search for plans created by Charles.Adcock, all of the dates for Date To Be Implemented show up 12/31/1969.  Charles had the same thing pulled up on his machine and the dates showed corrected.  

Sewelo was using a non-city machine and logged in as himself.  

I tested the issue on my personal machine with my login, but could not duplicate the error.  Perhaps this means it has something to do with their logins.

They are not sure when the issues started as they just recently began using this field/data in their workflow.

**Comment by JMurk** [comment]
I have duplicated this error in IE anf Firefox.  Chrome seems to work OK.  

![image](https://cloud.githubusercontent.com/assets/5805454/13778992/37f338f4-ea8f-11e5-88ce-48fc9c415d5b.png)

Dave- Have Wachs use Chrome as a temporary work-around for now.

Jun-  Please investigate why the date to be implemented is not reading the correct dates in those browsers.

This bug is in both dev and prod environments.

**Comment by taojun545** [comment]
The date-parsing algorithms are different in those browsers. For example, the data string is "2014-07-17 00:00:00". When converting it into data object using: new Date("2014-07-17 00:00:00"), different browsers show below:
- Chrome: Thu Jul 17 2014 00:00:00 GMT-0400 (Eastern Daylight Time)
- Firefox: Date {Invalid Date}
- IE: [date] Invalid Date

I will fix it asap.

**Comment by taojun545** [comment]
Fixed the issue on dev. Pls check all three browsers.

**Comment by JMurk** [comment]
it is working in Chrome and IE now, but still not in Firefox.

**Comment by JMurk** [comment]
Confirmed complete on all three, please push to production.

**Comment by taojun545** [comment]
Update on prod.

**Comment by JMurk** [comment]
Confirmed complete in all.
